### ISSUE TITLE
`auto` keyword causes unnecessary copy

### ISSUE THREAD

**Issue by Flole998** [Homegear/libhomegear-base#17]
At several cases the use of the `auto` keyword causes a copy of the entire entry. What is probably intended is using `auto &` to create a pointer and save lots of overhead

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L560

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L584

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L608

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L584

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L719

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L735

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L751

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/ICentral.cpp#L1342

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L87

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L436

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L486

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L537

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L609

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L633

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L2452

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L3177

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L3224

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L3749

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/Peer.cpp#L486

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/Systems/PhysicalInterfaces.cpp#L153

https://github.com/Homegear/libhomegear-base/blob/16b3e21849cd510d1f389b22ce29bf50a983f667/src/DeviceDescription/ParameterCast.cpp#L963

**Comment by hfedcba** [comment]
True and its all replaced with a reference. Thank you!
