### ISSUE TITLE
Error Message for [General] Configuration Sections due to missing ID or type

### ISSUE THREAD

**Issue by rowilken** [Homegear/libhomegear-base#7]
Hi, 

I'm new to homegear and "accidentally" installed the latest nightly version instead of a stable release. Although everything works, I constantly get the following error in my logs:

Error: Physical interface with title “general” has no type or id set

As far as I can see, this has been introduced with a check for id or type for all sections by hfedcba on 26.08.2020, commit fa8fbeed79dd1ccdafeb8f24e1ac4eaf75175ccc in file  src/Systems/FamilySettings.cpp.

I think the 2 checks added in this commit need an exception for the [General] configuration sections.

Kind regards,
Roland

**Comment by aromanro** [comment]
It affects only logging, should not affect functionality. I'll change the code to avoid logging for [General].
