### ISSUE TITLE
Transfer-Encoding "trailers" detected as invalid

### ISSUE THREAD

**Issue by ghost** [Homegear/libhomegear-base#8]
I am currently trying to setup homegear as hassio plugin. On enabling connections to admin over an ingress
there is an error in the log files.

03/06/21 20:37:59.103 RPC Server (Port 2001): XML RPC Server: Could not process HTTP packet: Unknown value for HTTP header "Transfer-Encoding": trailers Buffer: GET / HTTP/1.1
Host: mydomain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: de-DE,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://mydomain.com/1aaa927d_homegear/admin/
upgrade-insecure-requests: 1
dnt: 1
TE: trailers
Cookie: ingress_session=xxx
...

The error is caused by the following code block:
https://github.com/Homegear/libhomegear-base/blob/593cbbf378572baec1cac48fc8c6def186e96e90/src/Encoding/Http.cpp#L675

There an else if with encoding "trailers" is missing.

**Comment by hfedcba** [comment]
Thanks! It's fixed with https://github.com/Homegear/libhomegear-base/commit/b8d1a70988d41671ded1908dd6ee69b426c7fdd4 and will be included in the next nightly.

Cheers,

Sathya
